"""Refreshing Item table

Revision ID: 147843e6910c
Revises: f294b3f7bf97
Create Date: 2023-09-06 05:41:50.593141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147843e6910c'
down_revision = 'f294b3f7bf97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###
