"""empty message

Revision ID: 4755a6357938
Revises: a7631872674d
Create Date: 2023-09-08 20:03:10.797633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4755a6357938'
down_revision = '879fd6bd096c'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('game_invitations',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'user_id')
    )
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('Pending', 'Active', 'Scheduled', name='status'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.drop_table('game_invitations')
    # ### end Alembic commands ###
