"""empty message

Revision ID: 59c68179a4c7
Revises: ff97bb2732c8
Create Date: 2023-09-09 05:36:49.207936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c68179a4c7'
down_revision = 'ff97bb2732c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarded', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('skill', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('skill')
        batch_op.drop_column('onboarded')

    # ### end Alembic commands ###
