"""empty message

Revision ID: 96d03a1dea8f
Revises: 4755a6357938
Create Date: 2023-09-08 21:48:58.565857

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '96d03a1dea8f'
down_revision = '4755a6357938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_invitations')
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', postgresql.ENUM('Pending', 'Active', 'Scheduled', name='status'), autoincrement=False, nullable=True))

    op.create_table('game_invitations',
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name='game_invitations_game_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='game_invitations_user_id_fkey'),
    sa.PrimaryKeyConstraint('game_id', 'user_id', name='game_invitations_pkey')
    )
    # ### end Alembic commands ###
